# Generated by Django 5.2 on 2025-05-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='chat_id',
            new_name='chat_ID',
        ),
    ]
