# Generated by Django 5.2 on 2025-05-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_chat_id_subscriber_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='chat_ID',
            new_name='chat_id',
        ),
    ]
